alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: gastby-app
region: blr
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: techswarn/gatsbysite-docker
  health_check:
    http_path: /
    initial_delay_seconds: 90
    timeout_seconds: 10
  http_port: 8000
  instance_count: 2
  instance_size_slug: professional-xs
  name: gatsbysite-docker2
  routes:
  - path: /gatsbysite-docker2
  source_dir: /